### ISSUE TITLE
Add suppport for resolveUsing() and displayUsing() functions

### ISSUE THREAD

**Issue by YarinceP** [Benjacho/belongs-to-many-field-nova#26] opened 2020-02-10 21:38 UTC
Hello, congratulations on this useful package.

I am trying to manipulate the labels that the edit view shows. How can I do it?
![edit](https://user-images.githubusercontent.com/28911286/74259299-4c3fc900-4cbd-11ea-8dab-ebd1991b2593.png)

I already managed to customize the list that shows my elements. but I can't customize the objects in the edit view.

![pillbox](https://user-images.githubusercontent.com/28911286/74259261-3fbb7080-4cbd-11ea-989e-b0380bfa3776.png)

![pillbox2](https://user-images.githubusercontent.com/28911286/74259313-5235aa00-4cbd-11ea-8e23-0d4c19216cd1.png)

**Comment by YarinceP** [comment] 2020-02-11 16:59
could you help me?

**Comment by Benjacho** [comment] 2020-02-11 17:24
Okey share what you were trying

**Comment by YarinceP** [comment] 2020-02-21 18:28
Hi @Benjacho , thank you for answering, what I am trying to do I described earlier.



> Hello, congratulations on this useful package.
> 
> I am trying to manipulate the labels that the edit view shows. How can I do it?
> ![edit](https://user-images.githubusercontent.com/28911286/74259299-4c3fc900-4cbd-11ea-8dab-ebd1991b2593.png)
> 
> I already managed to customize the list that shows my elements. but I can't customize the objects in the edit view.
> 
> ![pillbox](https://user-images.githubusercontent.com/28911286/74259261-3fbb7080-4cbd-11ea-989e-b0380bfa3776.png)
> 
> ![pillbox2](https://user-images.githubusercontent.com/28911286/74259313-5235aa00-4cbd-11ea-8e23-0d4c19216cd1.png)

**Comment by YarinceP** [comment] 2020-02-21 18:29
> Okey, comparte lo que estabas intentando

**Comment by YarinceP** [comment] 2020-02-21 18:32
@Benjacho If you need any specific clarification regarding my question, do not hesitate to tell me.

**Comment by YarinceP** [comment] 2020-02-24 15:53
Any update about this? @Benjacho

**Comment by techdaddies-kevin** [comment] 2020-02-24 20:13
I am also trying to achieve something similar. Basically, I have a computed property / Accessor on my related model and that is what I want to use to generate the options list.

**Comment by techdaddies-kevin** [comment] 2020-02-24 20:16
@YarinceP Can you share how you were able to customize the output of the dropdown? I am trying to use a computed property on the model to do this (And using the optionsLabel method on the BelongsToManyField class) but it's not working.

**Comment by YarinceP** [comment] 2020-02-24 20:25
Of course @techdaddies-kevin . I did it as follows:

add the following to the BelonsToManyField field in your nova resource
`->options(\App\User::getMunicipios())`

And then he performed a function in the model of his resource. Something like this:

```
public static function getMunicipios($columns=['*'])
    {
        return DB::table('municipios')
            ->join('estados', 'municipios.estado_id', '=', 'estados.id')
            ->select([
                DB::raw("municipios.id"),
                DB::raw("CONCAT(municipios.nombre,' - ',estados.nombre)  AS nombre")])
            ->get(is_array($columns) ? $columns : func_get_args());
    }
```

**Comment by techdaddies-kevin** [comment] 2020-02-24 21:00
Thanks @YarinceP that helped me tremendously!

@Benjacho I'll try to explain the issue a better to make it more clear what the problem is.

First, I have a custom method on my `Category` model. This method gets all of my categories, but then changes the name property of each of them to indicate their tiers. 
![image](https://user-images.githubusercontent.com/1930280/75189977-bd539780-5725-11ea-8b9e-f269fda36e36.png)

This works great for generating the dropdown, but the problem is that once you've saved the relationship and reload the form, the text input doesn't show the full item shown in the dropdown, it only shows the value from the name column
![image](https://user-images.githubusercontent.com/1930280/75190634-140da100-5727-11ea-9729-5a0aa1450e30.png)

I tried to use the `optionsLabel` method to get the value using a computed property on the model, but it didn't work.

**Comment by Benjacho** [comment] 2020-03-19 18:01
Hey could you modify the title method of your reslationship resource to fit with your needs, to display field value names, we are using title method

**Comment by techdaddies-kevin** [comment] 2020-03-19 18:26
Not really - If we change the Title attribute it's going to change that title everywhere. We only need this Category > Sub Category > Sub Sub Category organization for this dropdown. On the front-end of the site, we'd want the title to return just the title of that single category. The best solution for us is to allow the dropdown to use a custom attribute to generate the title for the selected items.

**Comment by Benjacho** [comment] 2020-03-25 15:45
You can create a function getFullNameAttribute(){ return $this->name . $this->last_name} and append it to model $appends = ['full_name'] it is a mutator

**Comment by techdaddies-kevin** [comment] 2020-03-25 18:37
@Benjacho Thank you. I had the custom attribute but I wasn't appending it, which is why it wasn't working. 

So now here is my situation:

I have a resource that already has two categories assigned to it.
I load the resource edit page, and the dropdown correctly shows the breadcrumbs like I'm wanting (For the two already-set relationships).
However, the DROPDOWN does not show the breadcrumb representation like I want. 

My opinion is that if the 'optionsLabel()' method is being called, that should also set the display value in the dropdown itself.

![image](https://user-images.githubusercontent.com/1930280/77572798-feb2a080-6ea5-11ea-8d74-81e241220d78.png)

Is there some other way to set the dropdown options that I'm missing? I don't want to update the `title` property of the resource because I only need to show this full representation in specific scenarios.

**Comment by Benjacho** [comment] 2020-04-21 20:36
did you use options method?

**Comment by mehranhadidi** [comment] 2020-05-04 08:20
@Benjacho Thank you. Appending the mutator fixed my issue.

**Closed** 2020-05-06 16:15 UTC
